'use client';

import { useCallback, useEffect, useState, useRef } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { Download, ArrowLeft, Loader2, Clock, Info } from 'lucide-react';
import Link from 'next/link';

interface Summary {
  summary: string;
  key_points: string[];
  action_items: string[];
  sentiment: string;
}

interface Transcript {
  id: string;
  text: string;
  speaker: string;
  created_at: string;
  confidence: number;
}

interface Recording {
  id: string;
  audio_url: string | null;
  duration: number | null;
  file_size: number | null;
  format: string | null;
  created_at: string;
  status?: 'uploading' | 'completed' | 'failed' | null;
  recorded_by?: string | null;
}

export default function MeetingSummary() {
  const params = useParams();
  const searchParams = useSearchParams();
  const roomId = params.roomId as string;
  const isLastParticipantParam = searchParams.get('isLastParticipant') === 'true';

  const [meeting, setMeeting] = useState<any>(null);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [transcripts, setTranscripts] = useState<Transcript[]>([]);
  const [recordings, setRecordings] = useState<Recording[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [isMeetingEnded, setIsMeetingEnded] = useState(false);
  const hasAutoGeneratedRef = useRef(false);

  const supabase = createClient();

  // Determine if user should see full content (last participant or meeting ended)
  const canViewFullContent = isLastParticipantParam || isMeetingEnded;

  const loadData = useCallback(async () => {
    try {
      console.log('🔍 Loading data for room:', roomId);

      // Load meeting details
      const { data: meetingData, error: meetingError } = await supabase
        .from('meetings')
        .select('*')
        .eq('room_id', roomId)
        .single();

      if (meetingError) {
        console.error('❌ Error loading meeting:', meetingError);
        return;
      }

      console.log('✅ Meeting loaded:', meetingData);
      setMeeting(meetingData as any);
      setIsMeetingEnded((meetingData as any).status === 'ended');

      if (!meetingData) return;

      // Load transcripts
      console.log('🔍 Loading transcripts for meeting:', (meetingData as any).id);
      const { data: transcriptData, error: transcriptError } = await supabase
        .from('transcripts')
        .select('*')
        .eq('meeting_id', (meetingData as any).id)
        .order('created_at', { ascending: true });

      if (transcriptError) {
        console.error('❌ Error loading transcripts:', transcriptError);
      } else {
        console.log('✅ Transcripts loaded:', transcriptData?.length || 0);
        setTranscripts(transcriptData || []);
      }

      // Load recordings
      console.log('🔍 Loading recordings for meeting:', (meetingData as any).id);
      const { data: recordingData, error: recordingError } = await supabase
        .from('meeting_audio')
        .select('*')
        .eq('meeting_id', (meetingData as any).id)
        .order('created_at', { ascending: false });

      if (recordingError) {
        console.error('❌ Error loading recordings:', recordingError);
      } else {
        console.log('✅ Recordings loaded:', recordingData?.length || 0);
        setRecordings((recordingData as Recording[]) || []);
      }

      // Load summary if exists - use maybeSingle() instead of single()
      console.log('🔍 Loading summary for meeting:', (meetingData as any).id);
      const { data: summaryData, error: summaryError } = await supabase
        .from('meeting_summaries')
        .select('*')
        .eq('meeting_id', (meetingData as any).id)
        .maybeSingle();

      if (summaryError) {
        console.error('❌ Error loading summary:', summaryError);
      } else if (summaryData) {
        console.log('✅ Summary loaded:', summaryData);
        const data = summaryData as any;
        setSummary({
          summary: data.summary,
          key_points: data.key_points,
          action_items: data.action_items,
          sentiment: data.sentiment,
        });
      } else {
        console.log('ℹ️ No summary found for this meeting');
      }
    } catch (error) {
      console.error('💥 Failed to load data:', error);
    } finally {
      setLoading(false);
    }
  }, [roomId, supabase]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  // Auto-generate summary when last participant arrives and there's no summary yet
  useEffect(() => {
    if (
      !loading &&
      meeting &&
      canViewFullContent &&
      !summary &&
      transcripts.length > 0 &&
      !generating &&
      !hasAutoGeneratedRef.current
    ) {
      console.log('🤖 Auto-generating summary for last participant...');
      hasAutoGeneratedRef.current = true;
      generateSummaryAuto();
    }
  }, [loading, meeting, canViewFullContent, summary, transcripts, generating]);

  // Subscribe to meeting status changes (for early leavers waiting for meeting to end)
  useEffect(() => {
    if (!meeting?.id || isMeetingEnded) return;

    console.log('🔔 Subscribing to meeting status updates...');
    const channel = supabase
      .channel(`summary-meeting-status-${meeting.id}`)
      .on(
        'postgres_changes',
        {
          event: 'UPDATE',
          schema: 'public',
          table: 'meetings',
          filter: `id=eq.${meeting.id}`
        },
        (payload) => {
          const newStatus = payload.new as { status: string };
          if (newStatus.status === 'ended') {
            console.log('📢 Meeting ended! Refreshing data...');
            setIsMeetingEnded(true);
            loadData();
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [meeting?.id, isMeetingEnded, supabase, loadData]);

  async function generateSummaryAuto() {
    if (!meeting) return;

    try {
      setGenerating(true);

      const response = await fetch(`/api/meetings/${meeting.id}/summarize`, {
        method: 'POST',
      });

      if (!response.ok) throw new Error('Failed to generate summary');

      const data = await response.json();
      setSummary({
        summary: data.summary,
        key_points: data.keyPoints || [],
        action_items: data.actionItems?.map((item: any) => item.text) || [],
        sentiment: data.sentiment,
      });
    } catch (error) {
      console.error('Auto summary generation error:', error);
    } finally {
      setGenerating(false);
    }
  }

  async function generateSummary() {
    if (!meeting) return;

    try {
      setGenerating(true);

      const response = await fetch(`/api/meetings/${meeting.id}/summarize`, {
        method: 'POST',
      });

      if (!response.ok) throw new Error('Failed to generate summary');

      const data = await response.json();
      setSummary({
        summary: data.summary,
        key_points: data.keyPoints || [],
        action_items: data.actionItems?.map((item: any) => item.text) || [],
        sentiment: data.sentiment,
      });
    } catch (error) {
      console.error('Summary generation error:', error);
      alert('Failed to generate summary. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  async function downloadTranscript() {
    const text = transcripts
      .map((t) => `[${new Date(t.created_at).toLocaleTimeString()}] ${t.speaker}: ${t.text}`)
      .join('\n\n');

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `meeting_${roomId}_transcript.txt`;
    a.click();
  }

  const formatDuration = (duration: number | null) => {
    if (!duration || duration <= 0) return '—';
    const minutes = Math.floor(duration / 60);
    const seconds = duration % 60;
    if (minutes === 0) {
      return `${seconds}s`;
    }
    return `${minutes}m ${seconds.toString().padStart(2, '0')}s`;
  };

  const formatFileSize = (bytes: number | null) => {
    if (!bytes || bytes <= 0) return '—';
    const units = ['B', 'KB', 'MB', 'GB', 'TB'];
    const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
    const size = bytes / Math.pow(1024, index);
    return `${size.toFixed(1)} ${units[index]}`;
  };

  const hasPendingRecordings = recordings.some(
    (recording) => recording.status && recording.status !== 'completed'
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen bg-gray-50">
        <Loader2 className="animate-spin text-blue-500" size={48} />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-5xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <Link
            href="/dashboard"
            className="flex items-center gap-2 text-blue-600 hover:text-blue-700 mb-4 transition"
          >
            <ArrowLeft size={20} />
            Back to Dashboard
          </Link>

          <h1 className="text-3xl font-bold text-gray-900 mb-2">Meeting Summary</h1>
          <p className="text-gray-600">
            {meeting?.title} • {new Date(meeting?.created_at).toLocaleDateString()}
          </p>
        </div>

        {/* Meeting Status Banner for Early Leavers */}
        {!canViewFullContent && (
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
            <div className="flex items-start gap-3">
              <Clock className="text-blue-600 mt-0.5 flex-shrink-0" size={20} />
              <div>
                <h3 className="font-semibold text-blue-900">Meeting Still in Progress</h3>
                <p className="text-blue-700 text-sm mt-1">
                  You left before the meeting ended. The AI summary and recordings will be available once all participants have left.
                  You can view the transcript below in the meantime.
                </p>
                <p className="text-blue-600 text-xs mt-2 flex items-center gap-1">
                  <Loader2 className="animate-spin" size={12} />
                  Waiting for meeting to end...
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Summary Section */}
        <div className="bg-white rounded-lg shadow-lg p-6 mb-6 border border-gray-200">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-semibold text-gray-900">AI Summary</h2>
            {canViewFullContent && !summary && (
              <button
                onClick={generateSummary}
                disabled={generating || transcripts.length === 0}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition flex items-center gap-2"
              >
                {generating && <Loader2 className="animate-spin" size={16} />}
                {generating ? 'Generating...' : 'Generate Summary'}
              </button>
            )}
          </div>

          {!canViewFullContent ? (
            <div className="text-center py-8">
              <Info className="mx-auto text-gray-400 mb-3" size={32} />
              <p className="text-gray-500">
                AI summary will be generated when the meeting ends.
              </p>
              <p className="text-gray-400 text-sm mt-2">
                Check back after all participants have left the meeting.
              </p>
            </div>
          ) : summary ? (
            <div className="space-y-6">
              {/* Main Summary */}
              <div>
                <h3 className="font-semibold text-gray-700 mb-2">Overview</h3>
                <p className="text-gray-900">{summary.summary}</p>
              </div>

              {/* Sentiment */}
              <div>
                <h3 className="font-semibold text-gray-700 mb-2">Sentiment</h3>
                <span
                  className={`inline-block px-3 py-1 rounded-full text-sm font-medium ${
                    summary.sentiment === 'positive'
                      ? 'bg-green-100 text-green-700'
                      : summary.sentiment === 'negative'
                      ? 'bg-red-100 text-red-700'
                      : 'bg-gray-100 text-gray-700'
                  }`}
                >
                  {summary.sentiment}
                </span>
              </div>

              {/* Key Points */}
              {summary.key_points && summary.key_points.length > 0 && (
                <div>
                  <h3 className="font-semibold text-gray-700 mb-2">Key Points</h3>
                  <ul className="list-disc list-inside space-y-1 text-gray-900">
                    {summary.key_points.map((point, idx) => (
                      <li key={idx}>{point}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Action Items */}
              {summary.action_items && summary.action_items.length > 0 && (
                <div>
                  <h3 className="font-semibold text-gray-700 mb-2">Action Items</h3>
                  <ul className="list-disc list-inside space-y-1 text-gray-900">
                    {summary.action_items.map((item, idx) => (
                      <li key={idx}>{item}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ) : (
            <p className="text-gray-500 text-center py-8">
              {transcripts.length === 0
                ? 'No transcripts available for this meeting'
                : 'Click "Generate Summary" to create an AI-powered summary'}
            </p>
          )}
        </div>

        {/* Recordings Section */}
        <div className="bg-white rounded-lg shadow-lg p-6 mb-6 border border-gray-200">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-semibold text-gray-900">Meeting Recordings</h2>
            {canViewFullContent && recordings.length > 0 && (
              <span className="text-sm text-gray-500">{recordings.length} file(s)</span>
            )}
          </div>

          {!canViewFullContent ? (
            <div className="text-center py-8">
              <Info className="mx-auto text-gray-400 mb-3" size={32} />
              <p className="text-gray-500">
                Recordings will be available when the meeting ends.
              </p>
              <p className="text-gray-400 text-sm mt-2">
                Only the last participant to leave can upload recordings.
              </p>
            </div>
          ) : (
            <>
              {hasPendingRecordings && (
                <div className="flex items-center gap-2 text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-4 py-2 mb-4">
                  <Loader2 className="animate-spin" size={16} />
                  <span>Some recordings are still uploading. Refresh this page after a moment.</span>
                </div>
              )}

              {recordings.length > 0 ? (
            <div className="space-y-4">
              {recordings.map((recording) => {
                const status = recording.status || 'completed';
                const statusBadgeClass =
                  status === 'uploading'
                    ? 'bg-amber-100 text-amber-700'
                    : status === 'failed'
                    ? 'bg-red-100 text-red-700'
                    : 'bg-green-100 text-green-700';
                const statusLabel =
                  status === 'uploading'
                    ? 'Uploading'
                    : status === 'failed'
                    ? 'Failed'
                    : 'Completed';
                const canPlayMedia = status === 'completed' && Boolean(recording.audio_url);
                const formatLabel =
                  recording.format && recording.format.includes('/')
                    ? recording.format.split('/').join(' · ')
                    : recording.format;

                const recordedBy =
                  recording.recorded_by && meeting
                    ? recording.recorded_by === (meeting as any).host_id
                      ? 'Host'
                      : recording.recorded_by === (meeting as any).guest_id
                      ? 'Guest'
                      : 'Participant'
                    : null;

                return (
                  <div
                    key={recording.id}
                    className="border border-gray-100 rounded-lg p-4 flex flex-col gap-4 md:flex-row md:items-center md:gap-6"
                  >
                    <div className="flex-1">
                      <p className="text-gray-900 font-medium">
                        Recorded on {new Date(recording.created_at).toLocaleString()}
                      </p>
                      <div className="flex flex-wrap gap-4 text-sm text-gray-600 mt-2">
                        <span>Duration: {formatDuration(recording.duration)}</span>
                        <span>Size: {formatFileSize(recording.file_size)}</span>
                        {formatLabel && <span className="uppercase">{formatLabel}</span>}
                      </div>
                      <div className="mt-3 flex flex-wrap gap-2 items-center text-xs font-semibold">
                        <span className={`inline-flex items-center px-2 py-1 rounded-full ${statusBadgeClass}`}>
                          {statusLabel}
                        </span>
                        {recordedBy && (
                          <span className="text-gray-500 normal-case">Recorded by {recordedBy}</span>
                        )}
                      </div>
                      {status === 'uploading' && (
                        <p className="text-amber-700 text-sm mt-2 flex items-center gap-2">
                          <Loader2 className="animate-spin" size={16} />
                          Upload in progress. This recording will appear when processing finishes.
                        </p>
                      )}
                      {status === 'failed' && (
                        <p className="text-red-600 text-sm mt-2">
                          Upload failed. Please rejoin the meeting and try recording again.
                        </p>
                      )}
                    </div>
                    <div className="md:w-64 flex flex-col gap-2">
                      {canPlayMedia ? (
                        recording.format?.includes('video') ? (
                          <video
                            controls
                            src={recording.audio_url || undefined}
                            className="w-full rounded-lg bg-black"
                          />
                        ) : (
                          <audio controls src={recording.audio_url || undefined} className="w-full" />
                        )
                      ) : (
                        <div className="text-sm text-gray-500 text-center border border-dashed border-gray-200 rounded-lg py-6">
                          {status === 'uploading'
                            ? 'Upload in progress...'
                            : 'Recording unavailable.'}
                        </div>
                      )}
                      {canPlayMedia && recording.audio_url && (
                        <a
                          href={recording.audio_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-blue-600 hover:text-blue-700 text-sm font-medium text-center"
                        >
                          Download recording
                        </a>
                      )}
                    </div>
                  </div>
                );
              })}
              </div>
              ) : (
                <p className="text-gray-500 text-center py-6">
                  No recordings were saved for this meeting.
                </p>
              )}
            </>
          )}
        </div>

        {/* Transcript Section */}
        <div className="bg-white rounded-lg shadow-lg p-6 border border-gray-200">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-semibold text-gray-900">Full Transcript</h2>
            {transcripts.length > 0 && (
              <button
                onClick={downloadTranscript}
                className="flex items-center gap-2 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition"
              >
                <Download size={16} />
                Download
              </button>
            )}
          </div>

          {transcripts.length > 0 ? (
            <div className="space-y-4 max-h-96 overflow-y-auto">
              {transcripts.map((transcript, idx) => {
                // Determine if this is the first occurrence of this speaker
                const speakerIndex = transcripts
                  .slice(0, idx + 1)
                  .filter((t) => t.speaker === transcript.speaker).length;
                const isFirstSpeaker =
                  idx === 0 ||
                  transcripts.slice(0, idx).every((t) => t.speaker !== transcript.speaker);
                const speakerNumber =
                  [...new Set(transcripts.slice(0, idx + 1).map((t) => t.speaker))].indexOf(
                    transcript.speaker
                  ) + 1;

                return (
                  <div key={idx} className="flex gap-3">
                    <div className="flex-shrink-0">
                      <span
                        className={`inline-block px-2 py-1 rounded text-xs font-medium ${
                          speakerNumber === 1
                            ? 'bg-blue-100 text-blue-700'
                            : 'bg-green-100 text-green-700'
                        }`}
                      >
                        {speakerNumber === 1 ? 'Speaker 1' : 'Speaker 2'}
                      </span>
                    </div>
                    <p className="text-gray-900 flex-1">{transcript.text}</p>
                    <span className="text-gray-500 text-xs">
                      {new Date(transcript.created_at).toLocaleTimeString()}
                    </span>
                  </div>
                );
              })}
            </div>
          ) : (
            <p className="text-gray-500 text-center py-8">
              No transcript available for this meeting
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
